# Generated by Django 6.0.3 on 2026-03-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_address_booking_email_booking_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('09:00 AM - 10:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('12:00 PM - 01:00 PM', '12:00 PM - 01:00 PM'), ('02:00 PM - 03:00 PM', '02:00 PM - 03:00 PM'), ('03:00 PM - 04:00 PM', '03:00 PM - 04:00 PM'), ('04:00 PM - 05:00 PM', '04:00 PM - 05:00 PM'), ('05:00 PM - 06:00 PM', '05:00 PM - 06:00 PM')], default='09:00 AM - 10:00 AM', max_length=30),
        ),
    ]
