# Generated by Django 6.0.3 on 2026-03-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_booking_date_booking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('2 Wheeler', '2 Wheeler'), ('4 Wheeler', '4 Wheeler')], default='4 Wheeler', max_length=20),
        ),
    ]
