# Generated by Django 6.0.3 on 2026-03-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_booking_id_booking_charging_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], default='Prepaid', max_length=20),
        ),
    ]
